<?php
/**
 * Created by PhpStorm.
 * User: wufei
 * Date: 2/2/2017
 * Time: 3:07 PM
 */

namespace humhub\modules\devices\widgets;


use humhub\widgets\BaseMenu;
use Yii;

class ProfileReportMenu extends BaseMenu
{
    public $template = "@humhub/widgets/views/tabMenu";

    public $user;

    public function init()
    {

        $this->addItem(array(
            'label' => Yii::t('DevicesModule.widgets_ProfileReportMenu', 'Steps'),
            'url' => $this->user->createUrl('/devices/view/index'),
            'sortOrder' => 100,
            'isActive' => (Yii::$app->controller->action->id == 'index' && Yii::$app->controller->id === 'view'),
        ));

        $this->addItem(array(
            'label' => Yii::t('DevicesModule.widgets_ProfileReportMenu', 'Heart Rate'),
            'url' => $this->user->createUrl('/devices/view/heartrate'),
            'sortOrder' => 200,
            'isActive' => (Yii::$app->controller->action->id == 'heartrate' && Yii::$app->controller->id === 'view'),
        ));
        return parent::init(); // TODO: Change the autogenerated stub
    }
}