<?php
/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2015 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use humhub\modules\massuserimport\models\ExtendedUserInvite;
use humhub\modules\user\models\User;
use humhub\modules\massuserimport\Assets;

$noEntries = true;
Assets::register($this);
?>
<div class="panel panel-default">

    <div class="massuserimport-header">
        <h1><?php echo Yii::t('MassuserimportModule.base', '<strong>Invite</strong> users'); ?></h1>
    </div>

    <div class="panel-body">
        <?= \humhub\modules\admin\widgets\UserMenu::widget(); ?>
        <p/>

        <div class="alert alert-warning">
            <?php echo Yii::t('MassuserimportModule.base', 'Use the following form to upload a csv file containing the users you want to invite. Submit the form send an invitation email to each of them. '); ?>
        </div>

        <p>
            <?php echo Yii::t('MassuserimportModule.base', 'Download an example with additional information here:'); ?>
            <a
                class="btn btn-primary btn-xs tt"
                title="<?php echo Yii::t('MassuserimportModule.base', 'Download example'); ?>"
                href="<?php echo Url::toRoute(['/massuserimport/invite/download']) ?>"><i
                    class="fa fa-download"></i></a>
        </p>

        <?php
        $form = ActiveForm::begin([
            'enableAjaxValidation' => false,
            'options' => [
                'enctype' => 'multipart/form-data'
            ]
        ]);
        $form->setId('csv-form');
        ?>
        <div>
            <?= $form->field($model, 'csvFile', ['options' => ['class' => empty($model->errors) ? "" : $form->errorCssClass]])->fileInput() ?>
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
        <div class="error-summary" style="display:<?php echo empty($model->errors) ? "none" : "block" ?>">
            <hr/>
            <div class="alert alert-danger"><?php echo Yii::t('MassuserimportModule.base', 'Errors occurred.'); ?>
            <ul>
                <?php

                foreach ($model->errors as $key => $error)
                    echo '<li>' . $error . '</li>';
                ?>
            </ul>
            </div>
        </div>
        <?php ActiveForm::end(); ?>

        <?php if ($dataProviderMassInvite->totalCount > 0) {
            $noEntries = false;
            ?>
            <hr/>
            <p>
                <strong><?php echo Yii::t('MassuserimportModule.base', 'Mass invites'); ?></strong>
            </p>
            <p>
                <?php echo Yii::t('MassuserimportModule.base', 'Below you can see all currently pending invitations generated by the mass user invite module.'); ?>
            </p>
            <!-- form -->
            <?php
            echo GridView::widget([
                'id' => 'pending-invitations-id',
                'tableOptions' => [
                    'class' => 'table table-hover',
                ],
                'dataProvider' => $dataProviderMassInvite,
                'filterModel' => $searchModel,
                'columns' => [
                    'firstname',
                    'lastname',
                    'email',
                    [
                        'label' => 'Sender',
                        'content' => function ($model) {
                            $user = User::findOne([
                                'id' => $model->user_originator_id
                            ]);
                            return empty($user) ? Yii::t('yii', '(not set)') : $user->email;
                        }
                    ],
                    [
                        'header' => 'Actions',
                        'template' => '{resend} {delete} ',
                        'options' => ['style' => 'width:58px; min-width:58px;'],
                        'class' => 'yii\grid\ActionColumn',
                        'buttons' => [
                            'resend' => function ($url, $model) {
                                $confirm_link = \humhub\widgets\ModalConfirm::widget(array(
                                    'uniqueID' => 'modal_inviteresend' . $model->id,
                                    'linkOutput' => 'a',
                                    'cssClass' => 'btn btn-primary btn-xs tt" title="' . Yii::t('MassuserimportModule.base', 'Resend invitation'),
                                    'title' => Yii::t('MassuserimportModule.base', '<strong>Confirm</strong> resending invitation to %email%', [
                                        '%email%' => $model->email
                                    ]),
                                    'message' => Yii::t('MassuserimportModule.base', 'Do you want to resend the invitation mail to %email%?', [
                                        '%email%' => $model->email
                                    ]),
                                    'buttonTrue' => Yii::t('MassuserimportModule.base', 'Ok'),
                                    'buttonFalse' => Yii::t('MassuserimportModule.base', 'Cancel'),
                                    'linkContent' => '<i class="fa fa-envelope"></i>',
                                    'linkHref' => Url::toRoute([
                                        'resend',
                                        'id' => $model->id,
                                        'doit' => 2
                                    ])
                                ));
                                return $confirm_link;
                            },
                            'delete' => function ($url, $model) {
                                $confirm_link = \humhub\widgets\ModalConfirm::widget(array(
                                    'uniqueID' => 'modal_invitedelete' . $model->id,
                                    'linkOutput' => 'a',
                                    'cssClass' => 'btn btn-danger btn-xs tt" title="' . Yii::t('MassuserimportModule.base', 'Delete pending invite'),
                                    'title' => Yii::t('MassuserimportModule.base', '<strong>Confirm</strong> deleting pending invite of %email%', [
                                        '%email%' => $model->email
                                    ]),
                                    'message' => Yii::t('MassuserimportModule.base', 'Do you really want to delete this invite? This user can no longer join with his received invitation mail!'),
                                    'buttonTrue' => Yii::t('MassuserimportModule.base', 'Delete'),
                                    'buttonFalse' => Yii::t('MassuserimportModule.base', 'Cancel'),
                                    'linkContent' => '<i class="fa fa-times"></i>',
                                    'linkHref' => Url::toRoute([
                                        'delete',
                                        'id' => $model->id,
                                        'doit' => 2
                                    ])
                                ));
                                return $confirm_link;
                            }
                        ]
                    ]
                ]
            ]);
        }
        ?>

        <?php if ($dataProviderInvite->totalCount > 0) {
            $noEntries = false;
            ?>
            <hr/>
            <p>
                <strong><?php echo Yii::t('MassuserimportModule.base', 'User invites'); ?></strong>
            </p>
            <p>
                <?php echo Yii::t('MassuserimportModule.base', 'All invitations sent by users of the social network.'); ?>
            </p>
            <!-- form -->
            <?php
            echo GridView::widget([
                'id' => 'pending-invitations-id',
                'tableOptions' => [
                    'class' => 'table table-hover',
                ],
                'dataProvider' => $dataProviderInvite,
                'filterModel' => $searchModel,
                'columns' => [
                    'firstname',
                    'lastname',
                    'email',
                    [
                        'label' => 'Sender',
                        'content' => function ($model) {
                            $user = User::findOne([
                                'id' => $model->user_originator_id
                            ]);
                            return empty($user) ? "" : $user->email;
                        }
                    ],
                    [
                        'header' => 'Actions',
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{resend} {delete} ',
                        'options' => ['style' => 'width:56px; min-width:56px;'],
                        'buttons' => [
                            'resend' => function ($url, $model) {
                                $confirm_link = \humhub\widgets\ModalConfirm::widget(array(
                                    'uniqueID' => 'modal_inviteresend' . $model->id,
                                    'linkOutput' => 'a',
                                    'cssClass' => 'btn btn-primary btn-xs tt" title="' . Yii::t('MassuserimportModule.base', 'Resend invite email'),
                                    'title' => Yii::t('MassuserimportModule.base', '<strong>Confirm</strong> resending invitation to %email%', [
                                        '%email%' => $model->email
                                    ]),
                                    'message' => Yii::t('MassuserimportModule.base', 'Do you want to resend the invitation mail to %email%?', [
                                        '%email%' => $model->email
                                    ]),
                                    'buttonTrue' => Yii::t('MassuserimportModule.base', 'Ok'),
                                    'buttonFalse' => Yii::t('MassuserimportModule.base', 'Cancel'),
                                    'linkContent' => '<i class="fa fa-envelope"></i>',
                                    'linkHref' => Url::toRoute([
                                        'resend',
                                        'id' => $model->id,
                                        'doit' => 2
                                    ])
                                ));
                                return $confirm_link;
                            },
                            'delete' => function ($url, $model) {
                                $confirm_link = \humhub\widgets\ModalConfirm::widget(array(
                                    'uniqueID' => 'modal_invitedelete' . $model->id,
                                    'linkOutput' => 'a',
                                    'cssClass' => 'btn btn-danger btn-xs tt" title="' . Yii::t('MassuserimportModule.base', 'Delete pending invite'),
                                    'title' => Yii::t('MassuserimportModule.base', '<strong>Confirm</strong> deleting pending invite of %email%', [
                                        '%email%' => $model->email
                                    ]),
                                    'message' => Yii::t('MassuserimportModule.base', 'Do you really want to delete this invite? This user can no longer join with his received invitation mail!'),
                                    'buttonTrue' => Yii::t('MassuserimportModule.base', 'Delete'),
                                    'buttonFalse' => Yii::t('MassuserimportModule.base', 'Cancel'),
                                    'linkContent' => '<i class="fa fa-times"></i>',
                                    'linkHref' => Url::toRoute([
                                        'delete',
                                        'id' => $model->id,
                                        'doit' => 2
                                    ])
                                ));
                                return $confirm_link;
                            }
                        ]
                    ]
                ]
            ]);
        }
        ?>

        <?php if ($dataProviderSelf->totalCount > 0) {
            $noEntries = false;
            ?>
            <hr/>
            <p>
                <strong><?php echo Yii::t('MassuserimportModule.base', 'Self registration'); ?></strong>
            </p>
            <p>
                <?php echo Yii::t('MassuserimportModule.base', 'All registration requests.'); ?>
            </p>
            <!-- form -->
            <?php
            echo GridView::widget([
                'id' => 'pending-invitations-id',
                'tableOptions' => [
                    'class' => 'table table-hover',
                ],
                'dataProvider' => $dataProviderSelf,
                'filterModel' => $searchModel,
                'columns' => [
                    'firstname',
                    'lastname',
                    'email',
                    [
                        'header' => 'Actions',
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{resend} {delete} ',
                        'options' => ['style' => 'width:56px; min-width:56px;'],
                        'buttons' => [
                            'resend' => function ($url, $model) {
                                $confirm_link = \humhub\widgets\ModalConfirm::widget(array(
                                    'uniqueID' => 'modal_inviteresend' . $model->id,
                                    'linkOutput' => 'a',
                                    'cssClass' => 'btn btn-primary btn-xs tt" title="' . Yii::t('MassuserimportModule.base', 'Resend invite email'),
                                    'title' => Yii::t('MassuserimportModule.base', '<strong>Confirm</strong> resending invitation to %email%', [
                                        '%email%' => $model->email
                                    ]),
                                    'message' => Yii::t('MassuserimportModule.base', 'Do you want to resend the invitation mail to %email%?', [
                                        '%email%' => $model->email
                                    ]),
                                    'buttonTrue' => Yii::t('MassuserimportModule.base', 'Ok'),
                                    'buttonFalse' => Yii::t('MassuserimportModule.base', 'Cancel'),
                                    'linkContent' => '<i class="fa fa-envelope"></i>',
                                    'linkHref' => Url::toRoute([
                                        'resend',
                                        'id' => $model->id,
                                        'doit' => 2
                                    ])
                                ));
                                return $confirm_link;
                            },
                            'delete' => function ($url, $model) {
                                $confirm_link = \humhub\widgets\ModalConfirm::widget(array(
                                    'uniqueID' => 'modal_invitedelete' . $model->id,
                                    'linkOutput' => 'a',
                                    'cssClass' => 'btn btn-danger btn-xs tt" title="' . Yii::t('MassuserimportModule.base', 'Delete pending invite'),
                                    'title' => Yii::t('MassuserimportModule.base', '<strong>Confirm</strong> deleting pending invite of %email%', [
                                        '%email%' => $model->email
                                    ]),
                                    'message' => Yii::t('MassuserimportModule.base', 'Do you really want to delete this invite? This user can no longer join with his received invitation mail!'),
                                    'buttonTrue' => Yii::t('MassuserimportModule.base', 'Delete'),
                                    'buttonFalse' => Yii::t('MassuserimportModule.base', 'Cancel'),
                                    'linkContent' => '<i class="fa fa-times"></i>',
                                    'linkHref' => Url::toRoute([
                                        'delete',
                                        'id' => $model->id,
                                        'doit' => 2
                                    ])
                                ));
                                return $confirm_link;
                            }
                        ]
                    ]
                ]
            ]);
        }
        ?>
        <?php if ($noEntries) { ?>
            <hr/>
            <p>
                <?php echo Yii::t('MassuserimportModule.base', 'There are currently no open invitations.'); ?>
            </p>
        <?php } ?>
    </div>
</div>