<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%creator% has created an user for you.' => '',
    '%sender% has invited you to join %appName%! Please click on the button below to proceed with the registration.' => '',
    '<strong>Api</strong> documentation' => '',
    '<strong>Confirm</strong> deleting pending invite of %email%' => '',
    '<strong>Confirm</strong> recover password action.' => '',
    '<strong>Confirm</strong> resending invitation to %email%' => '',
    '<strong>Import</strong> users' => '',
    '<strong>Invite</strong> users' => '',
    'A general error occurred.' => '',
    'A user was created for you.' => '',
    'Activate/deactivate json rest API.' => '',
    'All invitations sent by users of the social network.' => '',
    'All registration requests.' => '',
    'An empty line was ignored.' => '',
    'An error occurred.' => '',
    'An invitation has already been sent. If you want to resend it use the manual resend button.' => '',
    'An user with this email adress already exists.' => '',
    'Below you can see all currently pending invitations generated by the mass user invite module.' => '',
    'Below you can see all imported users. In case an user did not get the email notification, you can trigger a password recovery for that user from here.' => '',
    'Cancel' => '',
    'Column named %columnName% does not exist in model %modelClass%.' => '',
    'Configure the mass user import module here' => '',
    'Create Account' => '',
    'Delete' => '',
    'Delete pending invite' => '',
    'Do you really want to delete this invite? This user can no longer join with his received invitation mail!' => '',
    'Do you want to resend the invitation mail to %email%?' => '',
    'Documentation could not be found!' => '',
    'Download an example with additional information here:' => '',
    'Download example' => '',
    'Errors occurred.' => '',
    'Import users' => '',
    'Imported users' => '',
    'Info:' => '',
    'Invitation email could not be sent!' => '',
    'Invite users' => '',
    'JSON REST API is not activated!' => '',
    'Line %lineNumber% - ' => '',
    'Log in' => '',
    'Mass User Import Module Configuration' => '',
    'Mass invites' => '',
    'No details available.' => '',
    'Number of entires in CSV line not equal to entries in properties line (first line).' => '',
    'Ok' => '',
    'Password recovery failed.' => '',
    'Password to access the json API.' => '',
    'Resend invitation' => '',
    'Resend invite email' => '',
    'Rest Api documentation' => '',
    'Self registration' => '',
    'Send recover password email' => '',
    'The email address %email% is already in use.' => '',
    'The email to %email% could not be sent.' => '',
    'The entry could not be saved.' => '',
    'The user was successfully created with id %id%.' => '',
    'The user was successfully deleted. The user with email %newspaceowner% overtakes the ownership of the user\'s spaces.' => '',
    'The user was successfully updated.' => '',
    'There are currently no imported users.' => '',
    'There are currently no open invitations.' => '',
    'This Api offers methods to access the user database and create, delete and modify user data. The data format is json. The different methods are explained in the following section.' => '',
    'This will create a 24-hour recover password token and send a recover link for %email%.' => '',
    'Use the following form to upload a csv file containing the users you want to import. Submit the form to import all users to your database and send an email notification containing the login credentials to each of them.' => '',
    'Use the following form to upload a csv file containing the users you want to invite. Submit the form send an invitation email to each of them. ' => '',
    'User invites' => '',
    'User not found!' => '',
    'View user' => '',
    'Welcome to %appName%' => '',
    'Welcome to %appName%! Please click on the button below to login with your new username and password.' => '',
    'You must provide the email adress of a valid new space owner!' => '',
    'Your password: %password%.' => '',
    'Your username: %userName%.' => '',
];
