<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%creator% has created an user for you.' => '%creator% hat einen Account für dich angelegt.',
    '%sender% has invited you to join %appName%! Please click on the button below to proceed with the registration.' => '%sender% hat Sie eingeladen %appName% beizutreten! Bitte folgen sie dem Link um mit der Registrierung fortzufahren.',
    '<strong>Api</strong> documentation' => '<strong>Api</strong> Dokumentation',
    '<strong>Confirm</strong> deleting pending invite of %email%' => 'Löschen der Einladung von %email% bestätigen',
    '<strong>Confirm</strong> recover password action.' => 'Passwort zurücksetzen bestätigen',
    '<strong>Confirm</strong> resending invitation to %email%' => 'Erneutes Senden der Einladung an %email% bestätigen',
    '<strong>Import</strong> users' => '<strong>Benutzer</strong> importieren',
    '<strong>Invite</strong> users' => '<strong>Benutzer</strong> einladen',
    'A general error occurred.' => 'Ein allgemeiner Fehler ist aufgetreten.',
    'A user was created for you.' => 'Es wurde ein Account für dich angelegt.',
    'Activate/deactivate json rest API.' => 'Json Rest Api aktivieren/deaktivieren.',
    'All invitations sent by users of the social network.' => 'Alle von Benutzern verschickte Einladungen.',
    'All registration requests.' => 'Alle Registrierungsanfragen.',
    'An empty line was ignored.' => 'Eine leere Zeile wurde ignoriert.',
    'An error occurred.' => 'Ein Fehler ist aufgetreten.',
    'An invitation has already been sent. If you want to resend it use the manual resend button.' => 'Eine Einladung wurde bereits geschickt. Wenn Sie diese erneut versenden wollen, nutzen sie den manuellen Button.',
    'An user with this email adress already exists.' => 'Ein Benutzer mit dieser Email Adresse existiert bereits.',
    'Below you can see all currently pending invitations generated by the mass user invite module.' => 'Im Folgenden sind alle austehenden Einladungen zu sehen, die über eine CSV Datei automatisch erstellt wurden.',
    'Below you can see all imported users. In case an user did not get the email notification, you can trigger a password recovery for that user from here.' => 'In der Tabelle sind alle importierten Benutzer aufgelistet. Sollte ein Benutzer keine Email Benachrichtigung erhalten haben, können sie das Passwort für diesen Benutzer hier zurücksetzen.',
    'Cancel' => 'Abbruch',
    'Column named %columnName% does not exist in model %modelClass%.' => 'Das model %modelClass% hat kein Attribut %columnName%.',
    'Configure the mass user import module here' => 'Hier können Sie das Mass User Import Modul konfigurieren.',
    'Create Account' => 'Account erstellen',
    'Delete' => 'Löschen',
    'Delete pending invite' => 'Austehende Einladung löschen',
    'Do you really want to delete this invite? This user can no longer join with his received invitation mail!' => 'Wollen die diese Einladung wirklich löschen? Der Benutzer wird dann nicht mehr über den Link in seiner erhaltenen Email beitreten können.',
    'Do you want to resend the invitation mail to %email%?' => 'Möchten Sie die Einladung an %email% erneut verschicken?',
    'Documentation could not be found!' => 'Die Dokumentation konnte nicht gefunden werden.',
    'Download an example with additional information here:' => 'Download einer Beispieldatei mit weiteren Informationen:',
    'Download example' => 'Datei herunterladen',
    'Errors occurred.' => 'Es sind Fehler aufgetreten.',
    'Import users' => 'Benutzer importieren',
    'Imported users' => 'Importierte Benutzer',
    'Info:' => 'Info:',
    'Invitation email could not be sent!' => 'Einladungs Email konnte nicht versendet werden!',
    'Invite users' => 'Benutzer einladen',
    'JSON REST API is not activated!' => 'Json Rest Api ist dekativiert!',
    'Line %lineNumber% - ' => 'Zeile %lineNumber% - ',
    'Log in' => 'Einloggen',
    'Mass User Import Module Configuration' => 'Konfiguration Mass User Import Modul ',
    'Mass invites' => 'Automatisch generierte Einladungen',
    'No details available.' => 'Keine Details verfügbar.',
    'Number of entires in CSV line not equal to entries in properties line (first line).' => 'Die Anzahl der Einträge in der CSV Zeile weicht von der Anzahl der in der ersten Zeile definierten Properties ab.',
    'Ok' => 'Ok',
    'Password recovery failed.' => 'Passwort zurücksetzen fehlgeschlagen.',
    'Password to access the json API.' => 'Passwort für Zugriff auf Json Rest Api.',
    'Resend invitation' => 'Einladung erneut verschicken',
    'Resend invite email' => 'Einladung erneut verschicken',
    'Rest Api documentation' => 'Json Rest Api Dokumentation',
    'Self registration' => 'Selbst angefragte Registrierungen',
    'Send recover password email' => 'Passwort zurücksetzen',
    'The email address %email% is already in use.' => 'Die Email Adresse %email% wird bereits verwendet.',
    'The email to %email% could not be sent.' => 'Die Email and %email% konnte nicht verschickt werden.',
    'The entry could not be saved.' => 'Der Datensatz konnte nicht gespeichert werden.',
    'The user was successfully created with id %id%.' => 'Der Account wurde erfolgreich mit der ID %id% angelegt.',
    'The user was successfully deleted. The user with email %newspaceowner% overtakes the ownership of the user\'s spaces.' => 'Der Account wurde erfolgreich gelöscht. Der Benutzer mit Email %newspaceowner% übernimmt alle seine Spaces.',
    'The user was successfully updated.' => 'Der Account wurde erfolgreich aktualisiert.',
    'There are currently no imported users.' => 'Es gibt noch keine importierten Benutzer.',
    'There are currently no open invitations.' => 'Es gibt aktuell keine offenen Einladungen.',
    'This Api offers methods to access the user database and create, delete and modify user data. The data format is json. The different methods are explained in the following section.' => 'Mit dieser Api können Benutzerdaten eingesehen und modifiziert und Benutzer erstellt und gelöscht werden. Das verwendete Datenformat ist Json. Im Folgenden werden die verfügbaren Methoden erklärt.',
    'This will create a 24-hour recover password token and send a recover link for %email%.' => 'Diese Aktion erstellt ein 24-h Token für %email%, mit welchem das Passwort zurückgesetzt werden kann. Der Benutzer wird per Email darüber informiert.',
    'Use the following form to upload a csv file containing the users you want to import. Submit the form to import all users to your database and send an email notification containing the login credentials to each of them.' => 'Bitte verwenden Sie das folgende Formular um eine CSV Datei hochzuladen, die die Benutzer die importiert werden sollen enthält. Beim Absenden des Formulars werden diese in der Datenbank angelegt und erhalten eine Benachrichtigungs Email mit den Logindaten.',
    'Use the following form to upload a csv file containing the users you want to invite. Submit the form send an invitation email to each of them. ' => 'Bitte verwenden Sie das folgende Formular um eine CSV Datei hochzuladen, die die Benutzer die eingeladen werden sollen enthält. Beim Absenden des Formulars erhalten diese eine Email mit einem Link über den sie sich registrieren können.',
    'User invites' => 'Von Benutzern verschickte Einladungen',
    'User not found!' => 'Account wurde nicht gefunden.',
    'View user' => 'Zum Profil',
    'Welcome to %appName%' => 'Wilkommen bei %appName%',
    'Welcome to %appName%! Please click on the button below to login with your new username and password.' => 'Wilkommen bei %appName%! Bitte klicke auf den Button um dich mit deinem neuen Benutzernamen und Passwort einzuloggen.',
    'You must provide the email adress of a valid new space owner!' => 'Es muss eine gültige Email Adresse für den neuen Space Eigentümer angegeben werden!',
    'Your password: %password%.' => 'Ihr Passwort: %password%',
    'Your username: %userName%.' => 'Ihr Benutzername: %userName%',
];
